### ISSUE TITLE
Great project, some suggestions

### ISSUE THREAD

**Issue by dot-mike** [Mqlhaha/downloader-ui#4]
Hello and thank you for this great contribution!
I have some suggestions:
Change `youtube-dl` to `yt-dp` ([see fork](https://github.com/yt-dlp/yt-dlp) and maybe not bind it to specific version)
https://github.com/Mqlhaha/downloader-ui/blob/cd9334372f6f8470ce525305923417b3fd9aaa67/src/requirements.txt#L34

I know Dockefile is up to each user, but maybe don't put a specific CDN located in China as default:
https://github.com/Mqlhaha/downloader-ui/blob/cd9334372f6f8470ce525305923417b3fd9aaa67/Dockerfile#L3
https://github.com/Mqlhaha/downloader-ui/blob/cd9334372f6f8470ce525305923417b3fd9aaa67/Dockerfile#L8

**Comment by Mqlhaha** [comment]
Thanks for your advice. I'm in China and sometimes it costs a lot of time to update software like pip and apk. So I added the CDN to build faster. I'll make another Dockerfile for China.

I didn't hear about ```yt-dp``` before but it seems to have much more functions. I'll read it later and decide if I should change to it.

Anyway, thanks for your advice.

**Comment by Mqlhaha** [comment]
commit 8557027405420971c6a24353e615f6672eb660de create a special version Dockerfile named ```Dockerfile.cn``` for Chinese users. In ```Dockerfile``` there's no CDN now.
