### ISSUE TITLE
Player.js 的固定播放链接

### ISSUE THREAD

**Issue by sicode** [Mqlhaha/downloader-ui#6]
![image](https://user-images.githubusercontent.com/3986116/109241107-b9b09000-7813-11eb-9900-3c491859729f.png)

是打算做下载完成后 在网页直接播放么？

**Comment by Mqlhaha** [comment]
原先的想法是做成下载后内置一个简单的播放器，通过点击Resouce.js中的Play跳转路由进行预览的，不过还没有实现；这个固定链接是拿来测试播放功能的

**Comment by sicode** [comment]
哦哦，期待
另外能多加个参数文本框么？
youtube-dl 和you-get 都有很多参数，希望能自己填

肯定不能做每个参数一个文本框填的了，那太复杂

**Comment by Mqlhaha** [comment]
commit 353e8b9fcd839e905e961e1b8fab1233e8090633 添加了输入自定义**额外**参数的功能
